### PR TITLE
Recipe for "requests"

### PR DESCRIPTION
**Pull request by thopiekar**
All done...

### CODE REVIEW

**Comment by thopiekar** [comment]
@awhiemstra I'm currently working on this plugin (also :roll_eyes: ): https://github.com/thopiekar/CuraFlashAirPlugin
But for a module there I need "requests". Got a OutputDevice module, which should work, but instead of extracting request from my Python installation or installing it from source on Windows, I thought I could directly add a recipe for it here. I'm sure "requests" could be also useful for other projects.

**Comment by awhiemstra** [comment]
Do you specifically need the requests package or just a way to make HTTP requests? For the UM3 network plugin we originally used requests iirc but then switched everything over to Qt's NetworkAccessManager, which turned out to have both a better API and be more performant. So you might want to consider doing the same.

For actually deciding to merge this, I am going to leave this to @Ghostkeeper .

**Comment by thopiekar** [comment]
@awhiemstra Yes, I do. I'm using https://github.com/TadLeonard/tfatool to communicate with the Wifi-SD-card. Of course, I could reinvent the wheel and rewrite everything, but I neither have the time nor I want to.
My test scripts are working fine already. As soon as I have time I can take my PPA and try it with Linux. There it is no problem to use the system or user installation of 3rd party modules inside Cura...

**Comment by awhiemstra** [comment]
@thopiekar So you actually need the requests package, which is fine but I was just double checking. ;)

**Comment by thopiekar** [comment]
:wave:

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4415. (I created that ticket 18 days ago but forgot to mention it here.)

**Comment by alekseisasin** [comment]
We also need to update AboutDialog.qml with information about this library.
If I'm correct you need to add:
projectsModel.append({ name:"Requests", description: catalog.i18nc("@label", "Python HTTP library"), license: "GPL", url: "http://docs.python-requests.org" });

**Comment by alekseisasin** [comment]
I added the information

**Comment by thopiekar** [comment]
Beautiful! Thanks guys! 🥇

**Pull request merged**
