### PR TITLE
Fixed references to SciPy and removed extra leading "h" on http

### PR DESCRIPTION
**Pull request by Darrell666**

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
@awhiemstra The CI tool waits indefinitely for user input due to this PR. It neatly asks whether we want to build this because building cura-build-environment takes a long time, but it doesn't allow for any user input.

**Comment by Ghostkeeper** [comment]
That hhttp link is pretty sloppy of us... Thanks!

**Comment by Ghostkeeper** [comment]
I'll let the CI test this...

**Comment by awhiemstra** [comment]
@Ghostkeeper: Yes it does, but you will need to go to the "old" UI for the job to actually get the "proceed" or "abort" links.

**Comment by awhiemstra** [comment]
In any case, I don't see much danger here so I am merging this.

**Pull request merged**
