### PR TITLE
README: Adding new deps

### PR DESCRIPTION
**Pull request by thopiekar**

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
So we depend on Git, Subversion AND Mercurial?! There's no download links for these deps that we can just wget/curl on?

**Comment by thopiekar** [comment]
Error messages were mentioning that {"hg", "svn", etc} were missing and builds failed. Installed them all with Chocolatey and everything was working well.
Well, we could bundle them into cura-build-environment, but it worked for me like this, so I don't care about something shiny.

**Comment by ChrisTerBeke** [comment]
Not shiny is OK for me, but needing 3 different versioning systems seems a bit weird :P

**Comment by awhiemstra** [comment]
It seems this has recently been fixed in upstream: https://github.com/python/cpython/commit/51599e2bdd10ab77212a7cbb41a13ea70ee13da8

I do not know where mercurial comes from though, as far as I know Python just uses git/svn and nothing else.

**Comment by thopiekar** [comment]
@ChrisTerBeke But that is life.. People are choosing different VCS.
Same with food.. After 10 months working at Ultimaker in NL, I still don't like cheese that much 😅 

@awhiemstra Who cares.. It is not a heavy dependency. Basically 2 clicks and installed 😃

**Comment by LipuFei** [comment]
@thopiekar This is built on the server, too. You want to install as few packages as possible on a build server, so I don't think Mercurial should be included.
As for your errors, which OS are you using? If you build with the current `master`, does it show those "missing hg and svn" errors? And do you know which package(s) and version(s) require them to build?

**Comment by thopiekar** [comment]
@LipuFei You updated Python since then, right?
Installed everything on the work laptop now. No hg needed anymore.

**Comment by LipuFei** [comment]
@thopiekar not updated yet. It's in a PR.

**Comment by thopiekar** [comment]
Hmm, then it is gone somehow. However, I corrected that.

**Comment by Ghostkeeper** [comment]
Git is not only needed for Windows, but on all platforms. Could you correct that, too?

**Pull request closed without merging**
