### PR TITLE
CURA-5321 update packages

### PR DESCRIPTION
**Pull request by LipuFei**
~- Add cryptography 2.2.2 with the following dependencies~
 ~- Add cffi 1.11.5~
 ~- Add asn1crypto 0.24.0~
~- Add pycparser 2.18~
~- Add pyjwt 1.6.1 (needs cryptography)~
~- Add pip 10.0.1~
 - Add idna 2.6
 - Update sip to 4.19.8
 - Update zeroconf to 0.20.0
 - Update python-utils to 2.3.0
 - Update six to 1.10.0
 - Update netifaces to 0.10.7
 - Update comtypes to 1.1.4
 - Update pyserial to 3.4
 - Update numpy-stl to 2.4.1
 - Fix compiling and installing OpenSSL 1.0.2k on Windows

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
As discussed during the standup we no longer require cryptography to be in the build environment, we're now using a special API endpoint to do that server side instead. This PR can be closed or updated to only update the already existing dependencies. We do still require `requests` though, but that already existed.

**Comment by LipuFei** [comment]
We can include all the updates and exclude cryptography + jwt

**Comment by jackha** [comment]
Let's do it!

**Comment by LipuFei** [comment]
This needs to be merged too: https://github.com/Ultimaker/cura-build/pull/177

**Comment by awhiemstra** [comment]
Note that you still have a few changes here that relate to crypto. Among others, you are now building OpenSSL twice since Python's build also builds OpenSSL.

**Comment by LipuFei** [comment]
@awhiemstra That's true, except that Python doesn't install OpenSSL library files but only the executables. I think perhaps we should compile OpenSSL first and then let Python use that to compile instead.

**Comment by LipuFei** [comment]
OpenSSL removed.

**Comment by Ghostkeeper** [comment]
This PR adds a few dependencies that are not used by Cura now: PythonCertifi, PythonChardet, PythonIdna, PythonPycparser and PythonUrllib3.

**Comment by LipuFei** [comment]
They are required by `requests`

**Comment by LipuFei** [comment]
I'll remove pycparser, missed it.

**Pull request merged**
