### PR TITLE
Update to Python 3.6.4

### PR DESCRIPTION
**Pull request by LipuFei**
Nice to have the new patch version.

### CODE REVIEW

**Comment by LipuFei** [comment]
CURA-4668

**Comment by LipuFei** [comment]
Well, now there is one more reason: #15. Some packages in the build environment depends on old libraries, so some of them cannot be compiled successfully on some most recent OSes and hardware.

**Comment by Ghostkeeper** [comment]
Can't we just update to 3.6 while we're at it?

I've been running that for half a year.

**Comment by ChrisTerBeke** [comment]
Also running 3.6 since the beginning, no issues.

**Comment by LipuFei** [comment]
Done, updated to 3.6.4

**Pull request merged**
